### ISSUE TITLE
Style improvement, ellipsis on too long class names

### ISSUE THREAD

**Issue by yuchi** [yui/yuidoc#41]
add

``` css
.apis a {
  text-overflow: ellipsis;
  overflow: hidden;
}
```

and a `title` attribute with the complete name to the links and you have no more overflow.
